PIDs:
  X:
    kp: -20.0 #-40
    kd: -10 #-20
    ki: -2 #-2
    minOutput: -10.0 #-10.0
    maxOutput: 10.0 #10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    kp: 20.0 # 20.0
    kd: 10.0 # 20.0
    ki: 2 # 2.0
    minOutput: -10.0 #-10.0
    maxOutput: 10.0 #10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp: -4000.0 #5000.0
    kd: -7000.0
    ki: -2000 # 3500.0
    minOutput: -20000.0 #10000
    maxOutput: 60000.0 #60000.0
    integratorMin: -100000.0
    integratorMax: 100000.0
  Yaw:
    kp: 20.0 #-200.0
    kd: 5.0 #-20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: -0.0
    integratorMax: 0.0
